// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJksdJpXwGHyHbrUD5kJ5W26nw37DFQV4',
    appId: '1:443007787394:web:756ab5b392c56094a76f9b',
    messagingSenderId: '443007787394',
    projectId: 'color-generator-17b00',
    authDomain: 'color-generator-17b00.firebaseapp.com',
    storageBucket: 'color-generator-17b00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsFY8Rjhr-FencysVr7Yoqu59Ilbi6ktU',
    appId: '1:443007787394:android:de6563020dd77453a76f9b',
    messagingSenderId: '443007787394',
    projectId: 'color-generator-17b00',
    storageBucket: 'color-generator-17b00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI0pMmdRZdiwXfKD4rHuYTOnb7H_b94Tk',
    appId: '1:443007787394:ios:1e4473be1f56e868a76f9b',
    messagingSenderId: '443007787394',
    projectId: 'color-generator-17b00',
    storageBucket: 'color-generator-17b00.appspot.com',
    iosClientId: '443007787394-hn8bus3bhvlth2kjbk81uajh90s46440.apps.googleusercontent.com',
    iosBundleId: 'colorgenerator.colorGenerator',
  );
}
